# Generated by Django 5.0.3 on 2024-03-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='renda_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Renda Mensal'),
        ),
    ]
